name: Build KPI-ORC EXE

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Recuperer le repo
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installer dependances
        run: |
          pip install pyinstaller
          pip install openpyxl

      - name: Lister fichiers (debug)
        run: dir

      - name: Compiler EXE
        run: pyinstaller --onefile --windowed --clean --name "KPI-ORC" main.py

      - name: Verifier dist
        run: dir dist

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: KPI-ORC-exe
          path: dist/*.exe
